### ISSUE TITLE
After roughly 24 hours of running, app crashed due to null reference

### ISSUE THREAD

**Issue by brasky** [OrbitGroup/TriangleCollector#11]
```
fail: Microsoft.Extensions.Hosting.Internal.Host[9]
      BackgroundService failed
      System.NullReferenceException: Object reference not set to an instance of an object.
         at TriangleCollector.Models.WebSocketAdapter.ReceiveAsync(MemoryStream ms, ArraySegment`1 buffer, CancellationToken cancellationToken) in C:\Users\ellio\source\repos\TriangleCollector\TriangleCollector\Models\WebSocketAdapter.cs:line 52
         at TriangleCollector.Services.USDMonitor.BackgroundProcessing(CancellationToken stoppingToken) in C:\Users\ellio\source\repos\TriangleCollector\TriangleCollector\Services\USDMonitor.cs:line 47
         at TriangleCollector.Services.USDMonitor.<>c__DisplayClass3_0.<<ExecuteAsync>b__1>d.MoveNext() in C:\Users\ellio\source\repos\TriangleCollector\TriangleCollector\Services\USDMonitor.cs:line 32
      --- End of stack trace from previous location ---
         at TriangleCollector.Services.USDMonitor.ExecuteAsync(CancellationToken stoppingToken) in C:\Users\ellio\source\repos\TriangleCollector\TriangleCollector\Services\USDMonitor.cs:line 30
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
crit: Microsoft.Extensions.Hosting.Internal.Host[10]
      The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at TriangleCollector.Models.WebSocketAdapter.ReceiveAsync(MemoryStream ms, ArraySegment`1 buffer, CancellationToken cancellationToken) in C:\Users\ellio\source\repos\TriangleCollector\TriangleCollector\Models\WebSocketAdapter.cs:line 52
         at TriangleCollector.Services.USDMonitor.BackgroundProcessing(CancellationToken stoppingToken) in C:\Users\ellio\source\repos\TriangleCollector\TriangleCollector\Services\USDMonitor.cs:line 47
         at TriangleCollector.Services.USDMonitor.<>c__DisplayClass3_0.<<ExecuteAsync>b__1>d.MoveNext() in C:\Users\ellio\source\repos\TriangleCollector\TriangleCollector\Services\USDMonitor.cs:line 32
      --- End of stack trace from previous location ---
         at TriangleCollector.Services.USDMonitor.ExecuteAsync(CancellationToken stoppingToken) in C:\Users\ellio\source\repos\TriangleCollector\TriangleCollector\Services\USDMonitor.cs:line 30
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
```

**Comment by brasky** [comment]
Resolved.
